[package]
name = "cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "axiom"
path = "src/main.rs"

[dependencies]
clap.workspace = true
inkwell.workspace = true
serde.workspace = true
toml.workspace = true
compiler.workspace = true
lsp.workspace = true