[package]
name = "lsp"
version.workspace = true
edition.workspace = true

[dependencies]
lsp-server.workspace = true
lsp-types.workspace = true
serde_json.workspace = true
anyhow.workspace = true
serde.workspace = true
compiler.workspace = true